version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: passroot 
      MYSQL_DATABASE: yii2basic 
    ports:
      - '3306:3306'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
